sabnzbd:
  image: "linuxserver/sabnzbd"
  container_name: "sabnzbd"
  volumes:
    - "./config/sabnzbd:/config"
    - "./data/_incoming:/downloads"
    - "./data/_incomplete:/incomplete-downloads"
    - "./data/shows:/tvshows"
    - "./data/movies:/movies"
  ports:
    - "8080:8080"
    - "9090:9090"
  environment:
    PGID: 1000
    PUID: 1000
  restart: always

sonarr:
  image: "linuxserver/sonarr"
  container_name: "sonarr"
  volumes:
    - "./config/sonarr:/config"
    - "./data/shows:/tv"
    - "./data/_incoming:/downloads"
  ports:
    - "8989:8989"
  environment:
    PGID: 1000
    PUID: 1000
  restart: always 
  links:
    - plex
    - sabnzbd

plex:
  image: "linuxserver/plex"
  container_name: "plex"
  volumes:
    - "./config/plex:/config"
    - "./data/shows:/data/tvshows"
    - "./data/movies:/data/movies"
  ports:
   - "32469:32469"
   - "32469:32469/udp"
 #  - "5353:5353/udp"
 #  - "1900:1900/udp"
   - "32400:32400"
   - "32400:32400/udp"
  environment:
    PGID: 1000
    PUID: 1000
  restart: always   
