version: '2'

secrets:
  trakt_client_id:
    file: ./.docker_secrets/trakt_client_id.txt
  trakt_client_secret:
    file: ./.docker_secrets/trakt_client_secret.txt

services:
  plex:
    image: "linuxserver/plex"
    container_name: "plex"
    volumes:
      - "./config/plex:/config"
      - "/volume1/photo:/data/photo"
      - "/volume1/video/documentaries:/data/documentaries"
      - "/volume1/video/movies:/data/movies"
      - "/volume1/video/tv:/data/tv"
      - "/volume1/video/videos:/data/videos"
    environment:
      PUID: 1033
      PGID: 100
      VERSION: "latest"
    restart: always
    network_mode: "host"
    devices:
      - "/dev/dri:/dev/dri"
    logging:
      driver: json-file

  sabnzbd:
    image: "linuxserver/sabnzbd"
    container_name: "sabnzbd"
    volumes:
      - "./config/sabnzbd:/config"
      - "/volume1/video/downloads/incoming:/downloads"
      - "/volume1/video/downloads/incomplete:/incomplete-downloads"
      - "/volume1/video/tv:/tv"
      - "/volume1/video/movies:/movies"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      PUID: 1033
      PGID: 100
    restart: always
    logging:
      driver: json-file
    mem_limit: 1000m

  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: "sonarr3"
    volumes:
      - "./config/sonarr:/config"
      - "/volume1/video/tv:/tv"
      - "/volume1/video/downloads/incoming:/downloads"
    ports:
      - "8989:8989"
    environment:
      PUID: 1033
      PGID: 100
    restart: always
    links:
      - sabnzbd
    logging:
      driver: json-file
    mem_limit: 500m

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      PUID: 1033
      PGID: 100
      TZ: "Europe/Berlin"
    volumes:
      - "./config/radarr:/config"
      - "/volume1/video/movies:/movies"
      - "/volume1/video/downloads/incoming:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped
    mem_limit: 500m

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      LOG_LEVEL: debug
      TZ: Europe/Berlin
    ports:
      - 5055:5055
    volumes:
      - "./config/overseerr:/app/config"
    links:
      - radarr
      - sonarr
    restart: unless-stopped
    mem_limit: 500m

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - "./config/tautulli:/config"
    environment:
      PUID: 1033
      PGID: 100
      TZ: Europe/Berlin
    ports:
      - 8181:8181
    mem_limit: 500m

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      PUID: 1033
      PGID: 100
      TZ: Europe/Berlin
    volumes:
      - "./config/bazarr:/config"
      - "/volume1/video/movies:/movies"
      - "/volume1/video/tv:/tv"
    ports:
      - 6767:6767
    links:
      - radarr
      - sonarr
    mem_limit: 500m
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      PUID: 1033
      PGID: 100
      TZ: Europe/Berlin
      AUTO_UPDATE: "true" # optional
      #RUN_OPTS: <run options here> # optional
    volumes:
      - ./config/jackett/config:/config
      - ./config/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    mem_limit: 500m

  rdtclient:
    container_name: rdtclient
    environment:
      PUID: 1033
      PGID: 100
      TZ: Europe/Berlin
    volumes:
      - './config/rdtclient/db/:/data/db'
      - '/volume1/video/downloads/incoming:/data/downloads' # for sonarr/radarr pickup
    image: rogerfar/rdtclient
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '6500:6500'
    restart: unless-stopped
